name: Verificador de Segurança "RumoLiberdade"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Configurando Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Instalando Dependências
      run: npm install

    - name: Verificando se o Código "Monta" (Build)
      run: npm run build
